### ISSUE TITLE
Duplicate opcode

### ISSUE THREAD

**Issue by oscarthorn** [50ButtonsEach/flic2-documentation#4]
Hi!

The spec seems to say that both `GetCurrentTimeRequest` and `SetAdvParametersRequest` have opcode 25. Is this a typo?

`#define OPCODE_TO_FLIC_GET_CURRENT_TIME_REQUEST 25`
`#define OPCODE_TO_FLIC_SET_ADV_PARAMETERS_REQUEST 25`

**Comment by Emill** [comment]
Yes, thanks! Fixed.
